
GET http://localhost:80/ HTTP/1.1

###

POST http://localhost:80/
Content-Type: application/json

{
    "name":"Shashank Sahu",
    "email":"shashankcs083@gmail.com",
    "mobileNo":"6307717181",
    
}


### Otp Sending Testing

POST http://localhost:80/auth/login/
Content-Type: application/json

{
    "mobileNo":"6394233643"
}


#### Otp Verification Testing

POST http://localhost:80/auth/verifyOTP/
Content-Type: application/json

{
    "mobileNo":"6394233643",
    "otp":"786141"
}


###

POST http://localhost:80/user/updateProfile/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtb2JpbGVObyI6IjYzMDc3MTcxNjEiLCJpYXQiOjE2MTkyNTUzOTd9.ZyDUMsTIfin-vA4uSikij-_-myYLLAZ1LFV7MIL0354

{
    "name":"Shashank Sahu",
    "mobileNo":"6307717161",
    "dob":"17/05/2000",
    "gender":"M"
}


### Guide Profile Creation

POST http://localhost:80/guide/updateProfile/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtb2JpbGVObyI6IjYzOTQyMzM2NDMiLCJpYXQiOjE2MTkyNjE2MTl9.9A7iLqDH8AMKpVB70q1_lbGVKPq4ZZwnsmCbUjOp9Pw

{
    "name":"Shobit Guide",
    "mobileNo":"6394233643",
    "dob":"17/05/1900",
    "gender":"M",
    "latitude": 80,
    "longitude": 80
}


### updateLocation


POST http://localhost:80/user/updateLocation/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtb2JpbGVObyI6IjYzOTQyMzM2NDMiLCJpYXQiOjE2MTkyNjE2MTl9.9A7iLqDH8AMKpVB70q1_lbGVKPq4ZZwnsmCbUjOp9Pw

{
    "latitude":80,
    "longitude":100
}


### get nearby Guides



POST http://localhost:80/user/searchGuides/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtb2JpbGVObyI6IjYzMDc3MTcxNjEiLCJpYXQiOjE2MTkyNTUzOTd9.ZyDUMsTIfin-vA4uSikij-_-myYLLAZ1LFV7MIL0354

{
    "latitude": 26.881481,
    "longitude": 80.992679
}

### switch active status of guide

POST http://localhost:80/guide/swithcActive/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtb2JpbGVObyI6IjYzOTQyMzM2NDMiLCJpYXQiOjE2MTkyNjE2MTl9.9A7iLqDH8AMKpVB70q1_lbGVKPq4ZZwnsmCbUjOp9Pw

{
    "active": false
}


