
GET http://localhost:80/ HTTP/1.1

###

POST http://localhost:80/
Content-Type: application/json

{
    "name":"Shashank Sahu",
    "email":"shashankcs083@gmail.com",
    "mobileNo":"6307717181"
}


### Otp Sending Testing

POST http://localhost:80/auth/login/
Content-Type: application/json

{
    "mobileNo":"6307717161"
}


#### Otp Verification Testing

POST http://localhost:80/auth/verifyOTP/
Content-Type: application/json

{
    "mobileNo":"6307717161",
    "otp":158415
}

